# Generated by Django 2.0 on 2021-08-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=80)),
                ('course', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'registration',
            },
        ),
    ]
