# Generated by Django 2.0 on 2021-08-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_registration_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cont',
            },
        ),
    ]
