# Generated by Django 2.0 on 2021-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='photo',
        ),
        migrations.AddField(
            model_name='registration',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='cont',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cont',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cont',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
