# Generated by Django 2.0 on 2021-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cont',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sub',
            name='email',
            field=models.CharField(default='', max_length=15),
        ),
    ]
