# Generated by Django 2.0 on 2021-08-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210827_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub',
            new_name='base',
        ),
        migrations.AlterModelTable(
            name='base',
            table='base',
        ),
    ]
