# Generated by Django 2.0 on 2021-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210830_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
    ]
