# Generated by Django 2.0 on 2021-08-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210831_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pic', models.ImageField(upload_to='prod/')),
            ],
            options={
                'db_table': 'prod',
            },
        ),
    ]
