# Generated by Django 4.2 on 2023-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='sci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pic', models.ImageField(upload_to='science/')),
            ],
            options={
                'db_table': 'sci',
            },
        ),
    ]
