# Generated by Django 3.2.4 on 2023-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_prod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='description',
            field=models.CharField(default='Description', max_length=10000),
        ),
    ]
