# Generated by Django 3.2.4 on 2023-06-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_prod_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sci',
        ),
    ]
